const SUPABASE_URL='https://opjbjvauridhhfoqyxmq.supabase.co';
const SUPABASE_KEY='sb_publishable_SEsM7VAb5ZFVJNpnNAxUOg_BjMDNlBc';
const API=SUPABASE_URL+'/rest/v1';
const H={apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':'application/json'};
let menus=[];const rp=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
function loginAdmin(e){e.preventDefault();if(user.value=='admin'&&pass.value=='admin123'){sessionStorage.admin=1;show()}else alert('Login salah.')}
function show(){login.style.display='none';dash.style.display='block';refresh()}
function logout(){sessionStorage.removeItem('admin');location.reload()}
if(sessionStorage.admin)show();
async function refresh(){try{let [mr,or]=await Promise.all([fetch(API+'/menus?select=*&order=id.asc',{headers:H}),fetch(API+'/orders?select=*,order_items(*)&order=id.desc',{headers:H})]);if(!mr.ok)throw new Error(await mr.text());if(!or.ok)throw new Error(await or.text());menus=await mr.json();let os=await or.json();menus=menus.filter(m=>m.category!=='Seblak'&&!/seblak/i.test(m.name));sm.textContent=menus.length;so.textContent=os.length;sr.textContent=rp(os.reduce((a,o)=>a+Number(o.total||0),0));table.innerHTML=`<table><tr><th>Menu</th><th>Foto</th><th>Kategori</th><th>Harga</th><th>Aksi</th></tr>${menus.map(m=>`<tr><td>${m.emoji||'🍲'} ${m.name}</td><td>${m.image_url?`<img src="${m.image_url}" style="width:70px;height:50px;object-fit:cover;border-radius:8px">`:'Belum ada'}</td><td>${m.category||''}</td><td>${rp(m.price)}</td><td><button onclick="edit(${m.id})">Edit</button> <button onclick="del(${m.id})">Hapus</button></td></tr>`).join('')}</table>`;orders.innerHTML=os.length?os.map(o=>`<div class="order"><b>BPM-${String(o.id).padStart(6,'0')} — ${o.customer_name}</b><br>📞 ${o.phone||''}<br>📍 ${o.address||''}<br>💳 ${o.payment_method||''}<br>📌 Status: ${o.status||'Menunggu'}<ul>${(o.order_items||[]).map(i=>`<li>${i.menu_name} × ${i.quantity}</li>`).join('')}</ul><b>Total: ${rp(o.total)}</b><br><small>${new Date(o.created_at).toLocaleString('id-ID')}</small></div>`).join(''):'<p class="empty">Belum ada pesanan.</p>'}catch(err){console.error(err);orders.innerHTML='<p class="empty">Data belum dapat dimuat. Periksa policy Supabase.</p>'}}
function openForm(id){let m=id&&menus.find(x=>x.id==id);eid.value=m?m.id:'';mn.value=m?m.name:'';mc.value=m?m.category:'Makanan';mp.value=m?m.price:'';me.value=m?m.emoji||'🍲':'🍲';md.value=m?m.description||'':'';window.currentImage=m?m.image_url||'':'';window.newImage=undefined;photo.value='';if(window.currentImage){preview.src=window.currentImage;preview.style.display='block'}else{preview.removeAttribute('src');preview.style.display='none'}mt.textContent=m?'Edit Menu':'Tambah Menu';modal.style.display='grid'}
function edit(id){openForm(id)}function closeForm(){modal.style.display='none'}
function previewPhoto(e){const file=e.target.files[0];if(!file)return;if(file.size>5*1024*1024)return alert('Ukuran foto maksimal 5 MB.');const r=new FileReader();r.onload=()=>{preview.src=r.result;preview.style.display='block';window.selectedFile=file};r.readAsDataURL(file)}
async function uploadImage(file){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path=Date.now()+'-'+safe;const r=await fetch(SUPABASE_URL+'/storage/v1/object/menu-images/'+path,{method:'POST',headers:{apikey:SUPABASE_KEY,Authorization:'Bearer '+SUPABASE_KEY,'Content-Type':file.type||'image/jpeg','x-upsert':'true'},body:file});if(!r.ok)throw new Error(await r.text());return SUPABASE_URL+'/storage/v1/object/public/menu-images/'+path}
async function saveMenu(e){e.preventDefault();try{let id=Number(eid.value);let image=window.currentImage||'';if(window.selectedFile)image=await uploadImage(window.selectedFile);let body={name:mn.value,category:mc.value,price:Number(mp.value),emoji:me.value,description:md.value,image_url:image};let r;if(id){r=await fetch(API+'/menus?id=eq.'+id,{method:'PATCH',headers:{...H,Prefer:'return=minimal'},body:JSON.stringify(body)})}else{r=await fetch(API+'/menus',{method:'POST',headers:{...H,Prefer:'return=minimal'},body:JSON.stringify(body)})}if(!r.ok)throw new Error(await r.text());window.selectedFile=null;closeForm();refresh()}catch(err){console.error(err);alert('Menu gagal disimpan: '+err.message)}}
async function del(id){if(!confirm('Hapus menu ini?'))return;try{let r=await fetch(API+'/menus?id=eq.'+id,{method:'DELETE',headers:H});if(!r.ok)throw new Error(await r.text());refresh()}catch(err){alert('Gagal menghapus menu. '+err.message)}}
async function clearOrders(){if(!confirm('Hapus semua pesanan?'))return;try{let r=await fetch(API+'/orders?id=not.is.null',{method:'DELETE',headers:H});if(!r.ok)throw new Error(await r.text());refresh()}catch(err){alert('Gagal menghapus pesanan. '+err.message)}}
